### ISSUE TITLE
Which additional features are needed?

### ISSUE THREAD

**Issue by MaStr** [miyovanstenis/the.wrong#1]
Do we need packages like:

 - imageboard (perl language?)
 - avahi (announcement via broadcast of the webserver)?
 - MediaServer (for media streaming using an extra app)

?

**Comment by Miyitus** [comment]
YesImageboard & mediaserver I don't know avahi -- I'll Google it-------- Mensaje original --------Asunto: [miyovanstenis/the.wrong] Which adonal features are needed? (#1)De: Matthias Strubel Para: "miyovanstenis/the.wrong" CC: Subscribed Do we need packages like:

imageboard (perl language?)
avahi (announcement via broadcast of the webserver)?
MediaServer (for media streaming using an extra app)

?

**Comment by MaStr** [comment]
Ok, so we are keeping the imageboard and the media server (minidlna).

**Comment by MaStr** [comment]
Any update on avahi?

**Comment by MaStr** [comment]
I removed avahi and depending packages from the installation.
