### ISSUE TITLE
Modify Ssid name

### ISSUE THREAD

**Issue by Miyitus** [miyovanstenis/the.wrong#10]
We will need to choose a way to modify the SSID name from the default "The.Wrong"

we'll like to keep The.Wrong as brand for the biennale and maybe add the ssid name to the default name, this will be specially for the institutions it will be like "The.Wrong/Valencia"

Can be with a txt or a php in the usb key directory for the software or what I think will be more interesting to change it on the custom insterface

**Comment by MaStr** [comment]
dublicate with #26
