### ISSUE TITLE
Wordpress with openwrt

### ISSUE THREAD

**Issue by MaStr** [miyovanstenis/the.wrong#16]
https://openwrt.org/docs/guide-user/services/webserver/install_wordpress

PreReq #15

**Comment by Miyitus** [comment]
Yes, I already install wordpress on my router but not very fan of the performance it takes a lot of time uploading files and it give some errors. So any other recommendations?

**Comment by MaStr** [comment]
Don’t use it. :-)
In this scenario, Wordpress is like a huge Elefant on a bicycle.

What do you want to achieve with Wordpress? What is the advantage of a big content management software?

**Comment by MaStr** [comment]
I think we can close this issue, because we want to go a different path, aren't we?

**Comment by MaStr** [comment]
Closed, not needed anymore
