### ISSUE TITLE
Test of plain image for factory delivery (2019-06-02)

### ISSUE THREAD

**Issue by MaStr** [miyovanstenis/the.wrong#18]
Hi Miyö,
please give the latest plain image a shot.

Those are located @ /TheWrong/Plain images/2019-06-02

What is new/special to those images?
No bigger changes, like we discussed, I only added a more concrete image tag to the .bin file. You can now find in `/etc/pbx_custom_image`

> PBX_auto_Image_2.7
> INSTALL_TARGET=plain

So you can verify after the installation, what the base image was.

Ok, how to test? On a brand new router: 

- Reflash via Gli.net firmware , uncheck "keep settings"

Reflash from a working PirateBox/the.Wrong setup

- Put device offline
- Remove USB stick, bring to your computer,
- Get a Backup of everything.
- Remove all files & folders
- Create *only* the folder called `auto_flash` 
- Place the plain image there
- Unmount safety
- put it back to your router and boot

After the reflash, you should have a steady power led. If you login via SSH to 192.168.1.1, you should find the lines above in /etc , then the reflash to the plain image worked.

Later you can place again a PirateBox .bin file to auto_flash and reinstall.

**Comment by MaStr** [comment]
If the plain image is working find, we can send it over to Gli.net for testing on their side..

**Comment by Miyitus** [comment]
ok! I'm on it rn

**Comment by MaStr** [comment]
Are there any open points here? If no, we can close this
