### ISSUE TITLE
pre_openwrt_init.sh hook with no effect

### ISSUE THREAD

**Issue by MaStr** [miyovanstenis/the.wrong#20]
If you perform a reconfiguration of the config file /etc/piratebox.conf , the changes do not have any effect. The configuration file needs to be reloaded afterwards. Also parts of the network configuration are already done and might needed to be redone.

Need to double check the script path and verify alternatives/fixes.

This prevents a custom path (<usb>/the.wrong) and other things. Stupid.

For LibraryBox, I created a complete new package file...

**Comment by Miyitus** [comment]
But this's for what version ? bc with my i modify your cong file, reboot and was perfect I change paths, ssid name etc

**Comment by Miyitus** [comment]
get it

**Comment by MaStr** [comment]
I’m trying to preconfigure the piratebox during the installation to the new SSID, which is not working as I expected.

**Comment by MaStr** [comment]
Solved with a custom package thewrong..ipkg
