### ISSUE TITLE
Testing new the.Wrong image (2019-06-05)

### ISSUE THREAD

**Issue by MaStr** [miyovanstenis/the.wrong#21]
Hi,
I uploaded a new set of file to our shared folder. 

The Piratebox .bin file and the install_the.wrong-complete.zip

You can upgrade/reinstall however you want. The Zip file contains multiple folders, which are all needed on the USB stick for the correct setup.

Changelog:

- Prohibit wifi clients talk to each other? #13 
- Custom Path on the USB stick #12    ; The content is located under usb/the.wrong ; I guess this is sufficient
- SSID "the.wrong" 
- Redirect to "the.wrong" hostname
- www_content from 2019-06-04
- Configure hostname in piratebox.conf #9
- Disable distribution of the custom index files, closes #17
- Disable Droopy (upload)
- Disable Shoutbox & avoid refreshing
- Disable JSON generation during boot, not needed.
- Change "nice" PirateBox Directory-Listing to a simple listing

**Comment by Miyitus** [comment]
tested & new issues opened

**Comment by MaStr** [comment]
- #22 
- #25 
- #23 
- #24
