### ISSUE TITLE
auto_flash && install time && load connection

### ISSUE THREAD

**Issue by Miyitus** [miyovanstenis/the.wrong#23]
After reset the router factory mode
I reflash and repared the auto_flash and install folder 

But this build it's working very slow, the installation took between 30 min-40min, after connected didn't open automatically the content folder, even to visualize the the files the router perform very badly.

**Comment by MaStr** [comment]
I can't verify that the router is performing badly. I did different tests yesterday, but it was ok.
I recognized, that the font file is the last file loaded from the router. That may have the impact of a slow pageload, but this is mostly client and HTML/JS related.

I also reduced the amount of services started by PirateBox, so in general it should be faster.
With the new image (I am currently preparing), the installer also installs less packages.

**Comment by MaStr** [comment]
And the overall performance is direct related to the performance of the USB stick. If that suffers because of being full or other things, the whole system may be slow...

**Comment by Miyitus** [comment]
i always use a clean usb to avoid any troubles. ive to.change the content anyway maybe its bc of the videos files.Enviado desde mi Huawei-------- Mensaje original --------Asunto: Re: [miyovanstenis/the.wrong] auto_flash && install time && load connection (#23)De: Matthias Strubel Para: "miyovanstenis/the.wrong" CC: Miyö Van Stenis ,Author And the overall performance is direct related to the performance of the USB stick. If that suffers because of being full or other things, the whole system may be slow...

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/miyovanstenis/the.wrong/issues/23?email_source=notifications\u0026email_token=AAIWQ67HM377AIS435GNCADPZC4C5A5CNFSM4HTX7U42YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXB7MTY#issuecomment-499381839",
"url": "https://github.com/miyovanstenis/the.wrong/issues/23?email_source=notifications\u0026email_token=AAIWQ67HM377AIS435GNCADPZC4C5A5CNFSM4HTX7U42YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXB7MTY#issuecomment-499381839",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by MaStr** [comment]
Ok, i do the same.
Mh.
