### ISSUE TITLE
User change the ssid

### ISSUE THREAD

**Issue by Miyitus** [miyovanstenis/the.wrong#26]
How can we set a file so the user can change the ssid 
it should be a site or we can add a php  like 

<?php

// URL
define('HOSTNAME', 'the.wrong');
define('USE_SSL', 0);

// Your current timezone
date_default_timezone_set('Europe/Spain');

// Manually add an admin account
//define('ADMIN_USERNAME', 'root');
//define('ADMIN_PASSWORD', 'password');

?>

**Comment by Miyitus** [comment]
!important 
As I mentioned we'll like to keep the.wrong as a prefix for the name but we'll like an easy way to change the name without ssh connection for BI iI have a php file to do this change

**Comment by MaStr** [comment]
Can you provide that PHP file? How is this solution done? what about permissions against the system?  How does the user authorize?
Lighttpd & PHP is running as non-root user (strongly recommend), so i doubt he can run uci commands for changing configuration.

**Comment by Miyitus** [comment]
Ok

I’ll upload to your server, the php involved on the ssid funtion and admin and let you check it out par exemple I set a function for BI with « openssl_random_pseudo_bytes » to create an user that could manage the router from the interface and so on and allows you between other things change the ssid from a php file called config

Check out the boostrap folder step6 and step7 there are the config we’re talking about that for BI did from the installation

Folder called PHP Wrong 


📎 MVS 👁
http://miyovanstenis.com/

De : Matthias Strubel
Envoyé le :05 June 2019 21:41
À : miyovanstenis/the.wrong
Cc : Miyö Van Stenis; Author
Objet :Re: [miyovanstenis/the.wrong] User change the ssid (#26)

Can you provide that PHP file? How is this solution done? what about permissions against the system? How does the user authorize?
Lighttpd & PHP is running as non-root user (strongly recommend), so i doubt he can run uci commands for changing configuration.

**Comment by MaStr** [comment]
First idea included via : 4149780
