### ISSUE TITLE
Captive Portal info Page => welcome.html not ok

### ISSUE THREAD

**Issue by MaStr** [miyovanstenis/the.wrong#27]
The custom welcome.html should be different

- The page is the landing page for the captive portal. This landing page needs to inform the user he is on an offline network. 
- The landing page should contain a "OK" Button or an automatic redirect to the content.
- The ok button or the redirect needs to serve this URL:  `"/captive/ia_handler.php?enter=1"`this automatically unlocks the captive portal and the device does/should not drop off the network.

The ia_handler.php will redirect to / which will redirect to the wished hostname

**Comment by MaStr** [comment]
I did a quick test with that

```HTML
        <html>
        <head><title>Redirect...</title>
        <meta http-equiv='refresh' content='0;url=/captive/ia_handler.php?enter=1' />
        <meta http-equiv='cache-control' content='no-cache, no-store, must-revalidate' />
        <meta http-equiv='pragma' content='no-cache' />
        <meta http-equiv='expires' content='0' />
        </head>
        <body>
        Redirect
        </body>
        </html>
```
And that was working quite nicely on my iOS


BTW: My iOS is doing an auto-login, which might also preventing a auto startup of the captive portal browser

**Comment by Miyitus** [comment]
Ok I’ll add the handler

📎 MVS 👁
http://miyovanstenis.com/

De : Matthias Strubel
Envoyé le :05 June 2019 22:22
À : miyovanstenis/the.wrong
Cc : Miyö Van Stenis; Assign
Objet :Re: [miyovanstenis/the.wrong] Captive Portal info Page =>welcome.html not ok (#27)

I did a quick test with that
        <html>
        <head><title>Redirect...</title>
        <meta http-equiv='refresh' content='0;url=/captive/ia_handler.php?enter=1' />
        <meta http-equiv='cache-control' content='no-cache, no-store, must-revalidate' />
        <meta http-equiv='pragma' content='no-cache' />
        <meta http-equiv='expires' content='0' />
        </head>
        <body>
        Redirect
        </body>
        </html>
And that was working quite nicely on my iOS

**Comment by MaStr** [comment]
BTW: My iOS is doing an auto-login, which might also preventing a auto startup of the captive portal browser
