### ISSUE TITLE
Testing the.wrong build (2019-06-07)

### ISSUE THREAD

**Issue by MaStr** [miyovanstenis/the.wrong#30]
I just uploaded a new build for you. This is already in the final zip based format.

/TheWrong/TheWrong_Builds/2019-06-07/

What has changed since the last build:

- The Zip file contains all needed files. The git.info file is a file for our development process and can be removed later. (Created a build script to reduce work time and get it reproducable)
- The.Wrong now has its own OpenWrt package including different dependencies.
- The new package is build through PirateBox build processes and shares the same scripts, so no redundant work.
- The folder "PirateBox" is now vanished.
- There were some issues with the captive portal, which should be better now.
- Hostname is now the.wrong not the.wrong.lan
- USB-Config files are available under <usb>/the.wrong/Config.  Just change them, when the device is offline on your computer, or remote via ssh/sftp and reboot afterwards.
   - Those configs are: ssid, txpower, channel, hostname
   - Please comment in #26 if that is suitable
- Lighttpd has an access.log available under <usb>/the.wrong/access.log 
- Lighttpd has a status page available under http://<hostname>/server-status
- avahi and dependencies were removed from install.
- simple way to query CaptivePortal database `php /opt/piratebox/bin/captive_cli.php show ww /opt/piratebox/` (if it shows 0, the device is simply not sending anything to trigger the captive portal feature.)

**Comment by Miyitus** [comment]
there's nothing on the folder, I want sunday to see if you were going to upload the files there but for today still empty

**Comment by Miyitus** [comment]
I found a few differences between the version I had and the one that it's in the factory folder, 
One of the diference between the two builds its that at the end of the installation in the directory the.wrong/board normally i only had the file kareha.pl but for the last version I've all files from kareha but with only Piratebox configuration.

However I didn't find any txt whom will allow me to modify default config. I check all txt files and directories please let me know what I've missed bc by now I only can change via ssh

**Comment by MaStr** [comment]
Thanks for testing.

Yes, the imageboard is now installed and should be 100% working. As requested, it is still included into the build.

About the config TXT files: ok, no worries, I’ll do a double check on my side... as soon as I can.

**Comment by MaStr** [comment]
I can confirm the missing txt files. Need to double check what's wrong
