### ISSUE TITLE
Image is processing the auto_package file, but renders unused

### ISSUE THREAD

**Issue by MaStr** [miyovanstenis/the.wrong#7]
The factory image build on 2019-05-28 starts installing packages, but ends up looking like an empty image file.

**Comment by MaStr** [comment]
For some reasons, the old box-installer version was pulled:

> Received message  <13>May 28 08:08:21 OpenWrt root: /bin/box_installer.sh : Creating opkg-lists folder, if missing 
> Received message  <13>May 28 08:08:21 OpenWrt root: **ls: Package.gz_*: No such file or directory** 
> Received message  <13>May 28 08:08:21 OpenWrt root: /bin/box_installer.sh : Trying to find next step 

> 
> $ ssh 192.168.1.1 opkg list
> Warning: Permanently added '192.168.1.1' (RSA) to the list of known hosts.
> base-files - 194.2-r7676-cddd7b4c77
> block-mount - 2018-12-28-af93f4b8-3
> **box-installer - 3.2.0-1**
> busybox - 1.28.4-3
> 

Box installer version 4.x is needed

**Comment by MaStr** [comment]
Ok, I found the reason why there is a difference.

I created the PirateBox image files including the install.zip file using the complete build chain of the openwrt-dev-environment repository. It changes the used repository implicitly to localhost to make use of the freshly build packages.
The plain image was build on the command line by hand, which was using the default development repository: development.piratebox.de , which has the old Box-Installer available.

**Comment by MaStr** [comment]
1. I made the domain developer.piratebox.de on my build-machine unavailable.
2. I created a new install_target for the image generation, which only contains the box installer and skips the install_zip generation. 
https://github.com/PirateBox-Dev/openwrt-image-build/commit/49596e0c7cb7615d8a446724bfbef7a891c3721d

This install target is referenced in 
3. https://github.com/PirateBox-Dev/openwrt-dev-environment/commit/6a8d9455d0e943620e945ce65597393d3e0b7c41  , where the plain images are now creating during the build scripts.

**Comment by MaStr** [comment]
Newer image builds will contain the install target in `/etc/pbx_custom_image` inside the .bin file.

https://github.com/PirateBox-Dev/openwrt-image-build/commit/8983d5ca52b4ff0f845d8e116812dcfba6c69634

**Comment by MaStr** [comment]
New Plain images uploaded. If the auto_flash is confirmed as working, then I'll close the issue

**Comment by Miyitus** [comment]
Ok, new plain image on TheWrong/auto_flash ... blinked for a couple of minutes and was fixed.
Same IP 192.168.1.1 for the commands to exe should i keep the "test" ?
"test -e /mnt/usb/install.log && rm -v /mnt/usb/install.log"

**Comment by MaStr** [comment]
The first plain image is broken in handling the auto_flash as well, which is the reason why you need to follow these steps with the new .bin from the provided plain files in any case:
https://github.com/miyovanstenis/the.wrong/issues/5#issuecomment-496646267

You only have to make sure you are copying the correct .bin file to /tmp for the later sysupgrade.

If you are flashing the device manually, you might not want to have the .bin file in auto_flash. But if you have you can then observe the automatic reflash (you only auto flash the just manually installed image again)
