### ISSUE TITLE
Testing plain image (again) from 2019-05-28-2

### ISSUE THREAD

**Issue by MaStr** [miyovanstenis/the.wrong#8]
New set of plain images without a specific brand.

/TheWrong/Plain images/2019-05-28-2

So basically, it contains all USB packages and the files for "extendRoot" and the "box-installer", which will kick-in for automatic reflash.

The automatic reflash is this mechanism: https://piratebox.cc/openwrt:diy#upgrade_piratebox
Pretty much straight forward. You can use this to upgrade from plain to PirateBox and backwards.

Changes:
 Fixed #7 
 Image-Brand is included into /etc/pbx_custom_image

Feedback & Quests welcome and here. Obvious bugs or things that necessarily needs to be changed, please open an issue.

best regards Matthias

**Comment by Miyitus** [comment]
It has run after the installation very well, Ive copy a lot of files to the usb key, test connections and by now its all good. 

I've done some modifications via ssh, however it always keeps the enthernet name by default of the router gl inet mt300n or sometimes said unidentified network but its only with the cable connection the wifi name its ok
